### PR TITLE
do not complain about quoted args like: ./wrapper.sh "apply -var a=b" en...

### PR DESCRIPTION
**Pull request by rhelmer**
...v role"

### CODE REVIEW

**Comment by jdotpz** [comment]
r+

**Comment by phrawzty** [comment]
This is the sort of stuff a bash linter might be able to catch. I suppose we could integrate the downloadable version of [ShellCheck](http://www.shellcheck.net/) into our CI flow?

In fact, running `wrapper.sh` through the checker reveals a number of potential double-quoting issues, heh.

**Comment by rhelmer** [comment]
@phrawzty that sounds great - I think we should definitely use a shell linter, I wasn't aware that there was a decent one out there.

**Pull request merged**
