### PR TITLE
fixes bug 1136371 - HSTS for a year

### PR DESCRIPTION
**Pull request by lonnen**
this fixes some merge conflicts that came up while peterbe's PR 262 was pending.

### CODE REVIEW

**Comment by peterbe** [comment]
👍 
I don't think we've had any problems with the current short HSTS limit. @milescrabill ?

**Comment by willkg** [comment]
Has the short HSTS limit actually been deployed in -prod for some period of time longer than a week? I'm not sure what's where these days.

**Comment by lonnen** [comment]
`git blame` says 24 days ago (Nov 14) which is newer than the latest tag

**Comment by lonnen** [comment]
The short HSTS limit was deployed today. Start your timers

**Pull request merged**
