### PR TITLE
Bug 1296238 - Refactored basic webapp configuration.

### PR DESCRIPTION
**Pull request by adngdb**
@jdotpz Does this look correct?

### CODE REVIEW

**Comment by adngdb** [comment]
@jdotpz I don't understand why this is failing, the error is not really helpful. Any idea?

**Comment by willkg** [comment]
@adngdb Travis is failing on a lint check on the puppet files. It's not related to your changes.

**Comment by jdotpz** [comment]
Travis-ci seems happy with this, so I'm good to let it ride with the next deploy.
Any objections?
@willkg @adngdb

**Comment by jdotpz** [comment]
(Note, my merge does not automagically send this to stage.  We will update the buildbox with this code if we are all in agreement)

**Comment by willkg** [comment]
It's going to take me a little bit to get through all this. I want to make sure that between these changes and the consulate changes proposed in bug 1296238:

1. there aren't any keys dropped by accident
2. there aren't any typos
3. that the processes end up with the correct configuration

I think that's going to take me a while to do. I think I can do this next week. Having said that, this isn't super high priority, so I'm inclined to push it off until after the work week.

If landing this blocks anything, I recommend reverting it for now.

**Comment by jdotpz** [comment]
This is not blocking anything for now, but if we're not going to touch it until post workweek, I'll go ahead and revert the merge.

**Comment by willkg** [comment]
@jdotpz Is it possible to reopen this pull request? I don't see a way to do that, but don't know if it's because of permissions issues.

**Comment by adngdb** [comment]
Reopened as #256.

**Pull request merged**
