### PR TITLE
Take advantage of a few new wins in terraform v0.5.0

### PR DESCRIPTION
**Pull request by jdotpz**
* Allow terraform to retry 5 times after transient AWS api errors
* Enable 30 second timeout connection draining on our elbs

### CODE REVIEW

**Comment by rhelmer** [comment]
@jdotpz so I am confused about the connection draining - does that come into play when making a new ELB, or is it for if terraform changes the AS associated with the ELB?

**Comment by rhelmer** [comment]
+1 on the retries, that's great

**Comment by jdotpz** [comment]
@rhelmer It is setup just once on a new ELB, but prior it was one of those "Do it yourself things" which I kept doing for testing.  Then, when you do an instance deregister from the elb, it doesn't just rip it out, it waits the timeout for connections to drain while it's taking no more new connects.

**Comment by rhelmer** [comment]
r+

**Comment by phrawzty** [comment]
very nice

**Pull request merged**
