### PR TITLE
Fixes bug 1175946 - Enabled Groovy scripting in our Elasticsearch clu…

### PR DESCRIPTION
**Pull request by AdrianGaudebert**
…sters.

@jp or @phrawzty r?

### CODE REVIEW

**Comment by AdrianGaudebert** [comment]
I have no idea how to test this though... I mean I know what to do to verify it solves my problem, and I have verified locally that this setting is the one, but I don't know how to specifically test this ``erb`` file. I suppose stage is the way to go?

**Comment by phrawzty** [comment]
> I suppose stage is the way to go? 

wisely

**Comment by jdotpz** [comment]
@phrawzty would you recommend just doing this manually on all existing nodes (stage first, as wisely chosen), or would you recommend bringing in new fresh nodes built from a new AMI with this manifest?

**Comment by phrawzty** [comment]
> @phrawzty would you recommend just doing this manually on all existing nodes (stage first, as wisely chosen), or would you recommend bringing in new fresh nodes built from a new AMI with this manifest?

Given how irritating it is to replace ES nodes, I would just apply the setting manually via an interface node.

**Comment by AdrianGaudebert** [comment]
@jdotpz so can we do this?

**Comment by jdotpz** [comment]
Sure.  @phrawzty apologies to be an ES noob...is that documented somewhere on the process to use to apply those settings to the whole cluster?

**Comment by phrawzty** [comment]
> Sure. @phrawzty apologies to be an ES noob...is that documented somewhere on the process to use to apply those settings to the whole cluster?

You just need to submit the config change via an HTTP interface as normal - it will be propagated to the rest of the cluster without further intervention.

**Comment by jdotpz** [comment]
Have a link to docs showing how?  I can look at configs and such to figure out parameter names.

**Comment by phrawzty** [comment]
> Have a link to docs showing how? I can look at configs and such to figure out parameter names.

The scripting engine (and config) has evolved quite a bit between [1.4](https://www.elastic.co/guide/en/elasticsearch/reference/1.4/modules-scripting.html) and 1.7(https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting.html) (current), so you'll really need to review the docs that pertain to the version that's currently deployed.

That said, upon further reflection, it's possible that this isn't a setting that can be applied dynamically (i.e. via POSTing to the interface), in which case the setting will need to be applied to the configs, followed by a rolling reload.

**Comment by jdotpz** [comment]
Sure, that I can do, and check cluster health during.  I'm going to wait until my irc client works before doing it, though.

**Comment by jdotpz** [comment]
I've manually updated stage elasticsearch cluster with this config, and in a gentle rolling fashion, recycled the process on the servers.

We're back to green health:
{
  "cluster_name" : "sss_stage",
  "status" : "green",
  "timed_out" : false,
  "number_of_nodes" : 8,
  "number_of_data_nodes" : 3,
  "active_primary_shards" : 45,
  "active_shards" : 90,
  "relocating_shards" : 2,
  "initializing_shards" : 0,
  "unassigned_shards" : 0
}

So we test this for a bit in stage, and then we do the same on prod.

**Comment by AdrianGaudebert** [comment]
I cannot fully verify that this works correctly without having https://github.com/mozilla/socorro-infra/pull/195 merged first. Though it seems the error I just got was a timeout and not an Elasticsearch error, I'd rather be sure. :)

**Comment by jdotpz** [comment]
Merged 195, waiting for a staging push for it.

**Comment by AdrianGaudebert** [comment]
So this actually cannot work, the setting I'm using is for ES 1.6+ and is not understood by ES 1.4. Discovered by talking with @phrawzty, confirmed with @peterbe in https://github.com/mozilla/socorro/pull/2926 and just now in sentry: https://errormill.mozilla.org/webtools/socorro-stage/group/399070/

Updating this PR in a few moments...

**Comment by AdrianGaudebert** [comment]
Updated, @jdotpz can we try this again? Sorry about the mess!

**Comment by peterbe** [comment]
I thought we had Groovy in production already. Didn't you need that to make certain fixes to super search fields which was resolved?

**Comment by AdrianGaudebert** [comment]
@jdotpz since this is resolved in production now, should we merge this PR?

**Pull request merged**
