### PR TITLE
Envbanner

### PR DESCRIPTION
**Pull request by jdotpz**

### CODE REVIEW

**Comment by phrawzty** [comment]
Looks like you've got trailing commits in this PR too...

**Comment by jdotpz** [comment]
But strangely no edits.  I think master already has those landed, and it didn't give me an option to squash them all.

**Comment by AdrianGaudebert** [comment]
@jdotpz that happened to me in the past, to solve it I would create a new branch from master and cherry-pick my commit there.

**Comment by jdotpz** [comment]
Good call, doing that here: https://github.com/mozilla/socorro-infra/pull/110

**Pull request closed without merging**
