### PR TITLE
bug 1176673 - bump idle timeout for symbol upload

### PR DESCRIPTION
**Pull request by rhelmer**
r? @jdotpz / @phrawzty

### CODE REVIEW

**Comment by phrawzty** [comment]
The diff is fine, but I'm curious about the value: why 600 seconds exactly?  Arbitrary or scientific? :smile:

**Comment by rhelmer** [comment]
@phrawzty per the bug, it looks like uploads are timing out around 3 minutes, so I meant to make this 300s. Not scientific per se just a nice round number.

**Comment by rhelmer** [comment]
@phrawzty rebased and pushed 300s

**Comment by jdotpz** [comment]
r+

**Pull request merged**
