### PR TITLE
Add app and project tags to terraform configs

### PR DESCRIPTION
**Pull request by jdotpz**

### CODE REVIEW

**Comment by rhelmer** [comment]
I'm not sure if we should use "crashreporter" for the project... we've used "socorro" historically (which is a codename I guess so kind of weird), I think people might confuse "crashreporter " for "crash-reports" aka "collector".

**Comment by jdotpz** [comment]
+1, updated that projectname.

**Comment by rhelmer** [comment]
r+++ would review again

**Comment by rhelmer** [comment]
@jdotpz want to squash this down to one commit? Also do you need me to merge or are you able to do that?

**Comment by phrawzty** [comment]
Before we merge I have a nit, heh.  I propose `s/app/role/` which is more in line with the established nomenclature of the rest of the project.

**Comment by jdotpz** [comment]
Sure, that's sensible.

**Comment by phrawzty** [comment]
Squash then `r+`.

**Comment by rhelmer** [comment]
This is done as part of #64 instead.

**Pull request closed without merging**
