### PR TITLE
bug 1136371 - enable HSTS for crash-stats

### PR DESCRIPTION
**Pull request by peterbe**
Much better place.

### CODE REVIEW

**Comment by willkg** [comment]
I don't really know much about nginx configuration. So while I could review this, I don't really know good from bad or how this affects our environment.

**Comment by peterbe** [comment]
Do you want to defer to Miles? 
I'm pretty confident this change is good though. It's what I use on a personal project.

**Comment by willkg** [comment]
One thing is that @milescrabil (wow--that's irritating, why isn't he listed in the github autocomplete) or @jdotpz should review this because they're the ops side.

While you might use it on your personal projects, that doesn't cover how this could affect the Socorro environment and users of Socorro.

The bedrock folks started with 1 day and watched for errors (I'm not sure what errors they watched for) and ratcheted it up from there after they were confident. Maybe that's a better path?

**Comment by peterbe** [comment]
@milescrabil is not in the autocomplete because he hasn't committed or participated in the git repo. 

We did a similar thing with air mozilla. First one 5 minutes, for a week then changed it up to on year. 

Also, I'm not sure this is OPs related. There are other webdev related things in there like [cache settings for example](https://github.com/peterbe/socorro-infra/commit/1199debc3b530f2bc25cf5f8929873a91f7dad7b)

In airmozilla, I did the security header stuff via Django code because I don't have access to the Apache config and it's inconvenient to communicate with them via webops bugzilla bugs.

**Comment by peterbe** [comment]
Updated. Let's see if there are any sites that NEED to access crash-stats.allizom.org or crash-stats.mozilla.org over HTTP.

**Comment by milescrabill** [comment]
@jvehent thoughts?

**Comment by jvehent** [comment]
This looks good to me. I usually don't use double-quotes in nginx values, so maybe just use `add_header Strict-Transport-Security max-age=86400;`

**Comment by peterbe** [comment]
[nginx-boilerplate](https://github.com/nginx-boilerplate/nginx-boilerplate/blob/master/boilerplate/enable/ssl.conf#L13) uses single quotes.

**Comment by milescrabill** [comment]
lgtm

**Comment by peterbe** [comment]
@milescrabill Feel free to merge this PR if you approve.

**Pull request merged**
